### ISSUE TITLE
Gotham 13.1 failed install. Dependencies not met.

### ISSUE THREAD

**Issue by GiJOr33** [xbmc-catchuptv-au/plugin.video.catchuptv.au.nine#1]
Hi,

Tried to install addon as zip file but got a dependencies not met. 
xbmc.log shows
"Addon script.module.brightcove requires xbmc python version 2.0 which is not available"

I've checked the addon.xml in this catchuptv nine addon and the line below exists
<import version="2.1.0" addon="xbmc.python"/>

Not sure what else to do to get it to install. Can I just remove that line?

**Comment by adammw** [comment]
@GiJOr33 I've released the addon to the repo now alongside the dependencies, so it should be easier to install now. Please test again and let me know if there's still any errors.

**Comment by GiJOr33** [comment]
Yep, all good and working from the repo. Thanks
