### ISSUE TITLE
Addon only accesses latest episodes, rather than all episodes.

### ISSUE THREAD

**Issue by Munkenmo** [xbmc-catchuptv-au/plugin.video.catchuptv.au.nine#15]
It seems the add on only navigates as far as the latest episodes for every show:

eg. The Block Season 14, latest episodes link is : https://www.9now.com.au/the-block/season-14   

but, the following URL gives access to all available episodes for the season : https://www.9now.com.au/the-block/season-14/episodes

**Comment by glennguy** [comment]
Hi @Munkenmo 
Thanks for letting us know. I've just pushed version 1.0.4 which addresses this. Please let us know if there's any further problems 😄

**Comment by Munkenmo** [comment]
Can confirm that all episodes are accessable and working perfectly now!  Thank you so much :D

**Comment by glennguy** [comment]
You're welcome, happy to help!
