### ISSUE TITLE
dependency not met

### ISSUE THREAD

**Issue by freddysmith1** [xbmc-catchuptv-au/plugin.video.catchuptv.au.nine#2]
![screen shot 2014-08-03 at 3 24 56 pm](https://cloud.githubusercontent.com/assets/8336824/3789930/eca494a6-1ad3-11e4-9cd2-4fc087c20701.png)
![screen shot 2014-08-03 at 3 34 14 pm](https://cloud.githubusercontent.com/assets/8336824/3789932/046fa8aa-1ad4-11e4-96e1-7a932d7029c0.png)

**Comment by adammw** [comment]
Hi @freddysmith1, is this still an issue for you? If installing from the repo, XBMC/Kodi should automatically pull down all the dependencies. If you still get a 'script failed' error, could you please upload your [log files](http://kodi.wiki/view/Log_file)?

**Comment by freddysmith1** [comment]
Shes all good mate
