### ISSUE TITLE
9Now icon not displayed on Matrix

### ISSUE THREAD

**Issue by michael-selig** [xbmc-catchuptv-au/plugin.video.catchuptv.au.nine#20]
The `<assets>` clause is missing from addon.xml. I added the following after the `<description>` to fix it:
```
<assets>
  <icon>icon.png</icon>
  <fanart>fanart.jpg</fanart>
</assets>
```

**Comment by glennguy** [comment]
Thanks @michael-selig - would you like to make a pull request for this?

**Comment by michael-selig** [comment]
I don't really know much about GIT, and have never made a pull request before, but I have done my best! I couldn't figure out how to link the issue with the patch.

**Comment by glennguy** [comment]
Looks good to me, merged a short while ago. You can reference the issue on GitHub just by writing the issue number with a hash before it - #21

**Comment by michael-selig** [comment]
Thanks :-)
