### ISSUE TITLE
Working on Helix?

### ISSUE THREAD

**Issue by mershedpaderder** [xbmc-catchuptv-au/plugin.video.catchuptv.au.nine#3]
Hi guys,
When attempting to install the repo i'm getting incorrect structure.
Is the repo and addons compatible with Helix yet?

Ryan

**Comment by adammw** [comment]
@mershedpaderder I just installed it on Kodi 14.2 on a OSX system and it appeared to work for me. If installing the repo isn't working, try installing from a ZIP file first (you may need to manually install the dependencies to get it to work though).

I'm going to close this issue for now, if you still have errors with the repo, please open an issue at https://github.com/xbmc-catchuptv-au/repo/issues/new

Thanks!
