### ISSUE TITLE
Can't play certain titles

### ISSUE THREAD

**Issue by jjcoolaus** [xbmc-catchuptv-au/plugin.video.catchuptv.au.nine#6]
Hi,
I'm getting an error trying to play certain titles on ninemsn, examples include:
Million Dollar Listing
Million Dollar Listing NY
The "bentwaters" episode of Storage Hunters UK (but not the "ipswitch" episode, that plays fine)
The "heart attack hotel" episode of Resort Rescue (but not the "rocky mountain high" episode, that plays fine)
There are probably many other examples of where some shows won't play at all, some episodes play fine and others don't, or every episode plays fine.

Ready for takeoff is an example of where every episode plays fine.

My log file is here: https://gist.github.com/jjcoolaus/fbc08f7b6990ba9d795e

(uploaded to github gist as per the instructions)

**Comment by andybotting** [comment]
Hi @jjcoolaus: looks like your log is cut off and missing all the good stuff. 

You could try using the Kodi Log Uploader (addon): http://kodi.wiki/view/Add-on:Kodi_Log_Uploader

**Comment by jjcoolaus** [comment]
Hi,
Thank you! I have installed the log uploader. I then tried 4 shows that I know don't work, then tried one that played perfectly, then tried another one that didn't work.
http://xbmclogs.com/pn4ivfset

Hopefully you can see all the logs this time and sorry about that, this is my first time uploading logs :)

Other troubleshooting steps tried:
uninstalling addon and reinstalling from the AU catchup repository
going to github, downloading a fresh zip, and installing from zip file
using the addon installer plugin (from tvaddons.ag) to install nine jumpin

Although my log here is from android, using iinet in Australia, I have also tried it on windows, android TV with kodi installed, and in terms of networks, iinet, TPG, Telstra 4G, Optus 4G, and expressvpn (via TPG) have all been tested. All work fine with other addins.

Please let me know if there is anything else I can do to help resolve this issue. Me and people in my family watch quite a lot from 9, and the regular jump in app buffers too much on ADSL (where the kodi addin works great, when it works)

Thanks for all your efforts here.

**Comment by andybotting** [comment]
Thanks, that looks better. 

This is one of @adammw 's addons. Unless he can see the problem quickly, I probably won't have time to look into it until Xmas
